### ISSUE TITLE
4/5/23 - Todo List

### ISSUE THREAD

**Issue by amaclean2** [amaclean2/BackyardFriends#133]
- [x] Get basic FE tests running on `<Mountains/>`
- [x] Make sure `byf-custom-logger` is operating correctly
- [ ] Ensure secrets are secured properly in both environments
